---
name: Deon
surname: Roos
position: "Senior Statistical Ecologist"
address: "Animal & Plant Health Agency, York"
email: "deonroos99@hotmail.com"
github: Deon88
orcid: 0000-0003-4866-7472
twitter: DeonRoos88
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "I am a statistical ecologist with experience and passion in teaching statistics, statistical consulting and developing statistical methodology for research. I have worked on a variety of research questions and data ranging from observational to experimental, empirical to theoretical, field based to lab-based. I am a proponent about scientific integrity, open data and code, and version control; This CV is version controlled and compiled with code."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = "E:\\DeonRoos_CV\\DeonRoos_CV_data.r")
```

# Employment

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )
```

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = title,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
  )
```

<!-- \pagebreak -->

<!-- # Skillset -->

```{r SKILLS, include = FALSE}
skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Awards & Funding

```{r HONORS}
honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    when = year,
    where = where
  )
```

# Publications

```{r WORKS}
works %>% #~author, ~title, ~year, ~where, ~doi,
  detailed_entries(
    with = author,
    when = year,
    what = title,
    why = doi,
    where = where
  )
```

# Contributions to scientific life

```{r PARTICIPATION}
partic %>% #~group, ~title, ~about, ~where,
  detailed_entries(
    with = title,
    when = year,
    what = group,
    why = about,
    where = where
  )
```

